replicaCount: 2

domain: "alda.app"

image:
  repositoryUrl: apitree-docker-local.jfrog.io
  tag: 0.1.0-alpha.4
  pullSecrets:
    server: "apitree-docker-local.jfrog.io"
    username: "admin"
    password: "V5A5YHUyY0"
    email: "a.dostal@apitree.cz"
