version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies from NPM
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run TSLint check
          command: npm run tslint:check
      - run:
          name: Run TSLint
          command: npm run tslint
      - run:
          name: Show prettier diff
          command: npm run prettier:show
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Add Coveralls token
          command: echo "${COVERALLS_REPO_TOKEN}" >> .coveralls.yml
      - run:
          name: Run test and coverage
          command: npm run coverage

  create_docker_image:
    working_directory: ~/docker-image
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login -u ${JFROG_USER} -p ${JFROG_PASS} ${JFROG_DOCKER_REPO}
      - run:
          name: Set docker image to workspace
          command: mkdir -p workspace && echo "${JFROG_DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}" > workspace/docker-image
      - run:
          name: Show docker image
          command: cat workspace/docker-image
      - run:
          name: Docker create image
          command: docker build --build-arg GIT_COMMIT=${CIRCLE_SHA1} --build-arg BUILD_NUM=${CIRCLE_BUILD_NUM} --build-arg BUILD_AUTHOR=${CIRCLE_USERNAME} -t $(cat workspace/docker-image):${CIRCLE_TAG:1} .
      - run:
          name: Docker push
          command: docker push $(cat workspace/docker-image)

  deploy_helm_chart:
    docker:
      - image: lachlanevenson/k8s-helm:latest
    working_directory: ~/helm
    steps:
      - checkout
      - run:
          name: Init Helm
          command: helm init --client-only
      - run:
          name: Set Helm Chart version
          command: sed -i -e "s/\${HELM_VERSION}/${CIRCLE_TAG:1}/g" .helm/${CIRCLE_PROJECT_REPONAME}/Chart.yaml
      - run:
          name: Show Chart.yaml
          command: cat .helm/${CIRCLE_PROJECT_REPONAME}/Chart.yaml
      - run:
          name: Package Helm Chart
          command: mkdir .helm/dist && helm package .helm/${CIRCLE_PROJECT_REPONAME}/ -d .helm/dist/
      - run:
          name: Install curl
          command: apk update && apk add curl curl-dev bash
      - run:
          name: Deploy Helm Chart
          command: curl -u ${JFROG_USER}:${JFROG_PASS} -T .helm/dist/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG:1}.tgz "${JFROG_HELM_REPO_LOCAL}/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG:1}.tgz"

  deploy_google_cloud_kubernetes:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/gc
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Auth to Google Cloud
          command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run:
          name: Set project
          command: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Set compute zone
          command: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Set container cluster
          command: gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - run:
          name: Install Helm
          command: |
            HELM_URL=https://storage.googleapis.com/kubernetes-helm
            HELM_TARBALL=helm-v2.9.0-linux-amd64.tar.gz
            STABLE_REPO_URL=https://kubernetes-charts.storage.googleapis.com/
            INCUBATOR_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com/
            apt update
            apt install -y wget
            wget -q ${HELM_URL}/${HELM_TARBALL}
            tar xzfv ${HELM_TARBALL}
            cp ./linux-amd64/helm /usr/local/bin/helm
            helm init --client-only
      - run:
          name: Add helm repository
          command: helm repo add --username ${JFROG_USER} --password ${JFROG_PASS} apitree ${JFROG_HELM_REPO}
      - run:
          name: Helm repo update
          command: helm repo update
      - run:
          name: Upgrade or install to Google Cloud
          command: helm upgrade --install --wait ${CIRCLE_PROJECT_REPONAME}-dev apitree/${CIRCLE_PROJECT_REPONAME} --devel --namespace ${CIRCLE_PROJECT_REPONAME}-dev --set image.tag=${CIRCLE_TAG:1},image.repositoryUrl=${JFROG_DOCKER_REPO},image.pullSecrets.server=${JFROG_DOCKER_REPO},image.pullSecrets.username=${JFROG_USER},image.pullSecrets.password=${JFROG_PASS},image.pullSecrets.email=${JFROG_EMAIL},domain=${DOMAIN}

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: apitree-aldo-context
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              only:
                - dev
      - create_docker_image:
          context: apitree-aldo-context
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
      - deploy_helm_chart:
          context: apitree-aldo-context
          requires:
            - create_docker_image
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
      - deploy_google_cloud_kubernetes:
          context: apitree-aldo-context
          requires:
            - deploy_helm_chart
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
