version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies from NPM
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run TSLint check
          command: npm run tslint:check
      - run:
          name: Run TSLint
          command: npm run tslint
      - run:
          name: Show prettier diff
          command: npm run prettier:show
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Add Coveralls token
          command: echo "${COVERALLS_REPO_TOKEN}" >> .coveralls.yml
      - run:
          name: Run test and coverage
          command: npm run coverage

  create_docker_image:
    working_directory: ~/docker-image
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ~/docker-image
      - run:
          name: Docker login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} ${DOCKER_URL}
      - run:
          name: Set docker image to workspace
          command: mkdir -p workspace && echo "${DOCKER_URL}/${CIRCLE_PROJECT_REPONAME}" > workspace/docker-image
      - run:
          name: Show docker image
          command: cat workspace/docker-image
      - run:
          name: Docker create image
          command: docker build --build-arg GIT_COMMIT=${CIRCLE_SHA1} --build-arg GIT_BRANCH=${CIRCLE_BRANCH} --build-arg BUILD_NUM=${CIRCLE_BUILD_NUM} --build-arg BUILD_AUTHOR=${CIRCLE_USERNAME} -t $(cat workspace/docker-image):${CIRCLE_BRANCH} .
      - run:
          name: Docker push
          command: docker push $(cat workspace/docker-image)
      - persist_to_workspace:
          root: .
          paths:
            - workspace
            - .circleci

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: apitree-aldo-context
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
      - dev_create_docker_image:
          context: apitree-aldo-context
          requires:
            - build
          filters:
            branches:
              only:
                - dev
