version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies from NPM
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run TSLint check
          command: npm run tslint:check
      - run:
          name: Run TSLint
          command: npm run tslint
      - run:
          name: Show prettier diff
          command: npm run prettier:show
      - run:
          name: Run build
          command: npm run build

workflows:
  version: 2
  build:
    jobs:
      - build
